version: '3'
services:

    mysql_newdocker:
      image: 'mysql:5.7'
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=demo
      ports:
        - "3307:3306"

    springboot_docker:
      image: spring-demo-docker
      ports: 
        - "8082:8082"
      environment: 
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql_newdocker:3306/demo?autoReconnect=true&useSSL=false 
         SPRING_DATASOURCE_USERNAME: "root"
         SPRING_DATASOURCE_PASSWORD: "root"
      build:
        context: "./"
        dockerfile: "Dockerfile"
      depends_on: 
          - mysql_newdocker 
